name: 'dbt_sales_analytics'
version: '1.0.0'
config-version: 2

profile: 'dbt_sales_analytics'

model-paths: ['models']
seed-paths: ['seeds']
test-paths: ['tests']
macro-paths: ['macros']

clean-targets:
  - 'target'
  - 'dbt_packages'

models:
  dbt_sales_analytics:
    staging:
      +materialized: view
    marts:
      +materialized: table

seeds:
  dbt_sales_analytics:
    +quote_columns: false